"""
seed_tools.py — export the current data.sqlite back into seed_data.py.

Called by setup.bat → option 3 ("Update seed_data.py").
Not used at runtime by the server.

Reads data.sqlite, then rewrites seed_data.py with the current contents.
Any custom edits you've made in the app become the new built-in defaults.
"""

import base64
import json
import sqlite3
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DB_FILE = BASE_DIR / "data.sqlite"
SEED_FILE = BASE_DIR / "seed_data.py"


def _q(s):
    """Quote a string safely for Python source."""
    return json.dumps("" if s is None else str(s), ensure_ascii=False)


def export_from_db():
    if not DB_FILE.exists():
        raise FileNotFoundError(f"{DB_FILE} not found.")

    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    try:
        c = conn.cursor()

        def rows(sql):
            return c.execute(sql).fetchall()

        pw_row = c.execute("SELECT value FROM meta WHERE key='password_b64'").fetchone()
        pw_b64 = pw_row["value"] if pw_row else "YWRtaW4xMjM="

        valves = [(r["name"], r["catalogue"], r["code"]) for r in rows("SELECT * FROM valves ORDER BY sort_order")]
        classes = [(r["name"], r["code"]) for r in rows("SELECT * FROM classes ORDER BY sort_order")]
        sizes = [(r["name"], r["code"]) for r in rows("SELECT * FROM sizes ORDER BY sort_order")]
        treatments = [(r["name"], r["code"]) for r in rows("SELECT * FROM treatments ORDER BY sort_order")]
        materials = [(r["material_group"], r["designation"], r["spec"], r["code"], r["form"])
                     for r in rows("SELECT * FROM materials ORDER BY sort_order")]
        part_headers = [r["header"] for r in rows("SELECT * FROM part_headers ORDER BY sort_order")]
        part_rows = [json.loads(r["cells"]) for r in rows("SELECT * FROM part_rows ORDER BY sort_order")]
        years = [r["value"] for r in rows("SELECT * FROM years ORDER BY sort_order")]
        project_types = [r["value"] for r in rows("SELECT * FROM project_types ORDER BY sort_order")]
    finally:
        conn.close()

    lines = []
    lines.append('"""')
    lines.append("seed_data.py — canonical reference data for the Part No. Generator.")
    lines.append("")
    lines.append("AUTO-GENERATED by setup.bat → option 3 (Update seed_data.py).")
    lines.append("Feel free to edit by hand, but running option 3 again will overwrite it.")
    lines.append('"""')
    lines.append("")
    lines.append(f'DEFAULT_PW_B64 = {_q(pw_b64)}   # base64 password (default "admin123")')
    lines.append("")

    def emit(name, items, formatter, comment):
        lines.append(f"# {comment}")
        lines.append(f"{name} = [")
        for it in items:
            lines.append("    " + formatter(it) + ",")
        lines.append("]")
        lines.append("")

    emit("VALVES", valves,
         lambda t: f"({_q(t[0])}, {_q(t[1])}, {_q(t[2])})",
         "Valve types: (name, catalogue, code)")

    emit("CLASSES", classes,
         lambda t: f"({_q(t[0])}, {_q(t[1])})",
         "Pressure classes: (name, code)")

    emit("SIZES", sizes,
         lambda t: f"({_q(t[0])}, {_q(t[1])})",
         "Nominal sizes: (name, code)")

    emit("TREATMENTS", treatments,
         lambda t: f"({_q(t[0])}, {_q(t[1])})",
         "Special treatments: (name, suffix)")

    emit("MATERIALS", materials,
         lambda t: f"({_q(t[0])}, {_q(t[1])}, {_q(t[2])}, {_q(t[3])}, {_q(t[4])})",
         "Materials: (group, designation, spec, code, form)")

    lines.append("# Part List column headers (valve catalogue codes)")
    lines.append("PART_HEADERS = [")
    for h in part_headers:
        lines.append("    " + _q(h) + ",")
    lines.append("]")
    lines.append("")

    lines.append("# Part List rows — one row per part")
    lines.append("PART_ROWS = [")
    for row in part_rows:
        lines.append("    " + json.dumps(list(row), ensure_ascii=False) + ",")
    lines.append("]")
    lines.append("")

    lines.append("# Year values for the Project NO. dropdown")
    lines.append("YEARS = [")
    for y in years:
        lines.append("    " + _q(y) + ",")
    lines.append("]")
    lines.append("")

    lines.append("# Project type letters")
    lines.append("PROJECT_TYPES = [")
    for p in project_types:
        lines.append("    " + _q(p) + ",")
    lines.append("]")
    lines.append("")

    SEED_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"[seed] wrote {SEED_FILE.name}: "
          f"{len(valves)} valves, {len(materials)} materials, "
          f"{len(part_rows)} part rows, {len(years)} years")


if __name__ == "__main__":
    export_from_db()