@echo off
setlocal EnableDelayedExpansion
title Part No. Generator - Setup
cd /d "%~dp0"

echo ============================================
echo   Part No. Generator - Setup
echo ============================================
echo.

REM ---------- Require administrator privileges ----------
net session >nul 2>nul
if %errorlevel% neq 0 (
  echo This setup must run as Administrator.
  echo.
  echo Right-click setup.bat and choose "Run as administrator".
  echo.
  pause
  exit /b 1
)

REM ---------- Menu ----------
echo What would you like to do?
echo.
echo   [1] Initial setup                (configure address, hosts, firewall)
echo   [2] Repair / Reset database      (rebuild data.sqlite from seed_data.py)
echo   [3] Update seed_data.py          (capture current DB as the new defaults)
echo   [4] Exit
echo.
set "MENU="
set /p "MENU=Choose [1/2/3/4] (default 1): "
if "!MENU!"=="" set "MENU=1"

if "!MENU!"=="1" goto INITIAL
if "!MENU!"=="2" goto REPAIR
if "!MENU!"=="3" goto UPDATESEED
if "!MENU!"=="4" exit /b 0

echo Invalid choice.
pause
exit /b 1


:INITIAL
echo.
echo ============================================
echo   Initial setup
echo ============================================
echo.

REM ---------- Ask for the address ----------
set "DEFAULT_HOST=part-generator.eng"
set "HOST="
set /p "HOST=Address to use [%DEFAULT_HOST%]: "
if "!HOST!"=="" set "HOST=%DEFAULT_HOST%"

REM ---------- Ask about the port ----------
echo.
echo How should the URL look?
echo.
echo   [1] http://%HOST%           (no port - requires forwarding port 80)
echo   [2] http://%HOST%:1030      (keeps :1030 in the URL, no forwarding)
echo.
set "PORTCHOICE="
set /p "PORTCHOICE=Choose [1/2] (default 1): "
if "!PORTCHOICE!"=="" set "PORTCHOICE=1"

if "!PORTCHOICE!"=="1" (
  set "USE_PORT_80=1"
  set "URL=http://%HOST%"
) else (
  set "USE_PORT_80=0"
  set "URL=http://%HOST%:1030"
)

REM ---------- Ask about LAN access ----------
echo.
echo Will other computers on the network use this app?
echo.
echo   [1] Yes - accessible from other computers on the LAN
echo   [2] No  - only reachable from this computer (default)
echo.
set "LANCHOICE="
set /p "LANCHOICE=Choose [1/2] (default 2): "
if "!LANCHOICE!"=="" set "LANCHOICE=2"

if "!LANCHOICE!"=="1" (
  set "BINDADDR=0.0.0.0"
  set "LANMODE=1"
) else (
  set "BINDADDR=127.0.0.1"
  set "LANMODE=0"
)

echo.
echo ---------------------------------------------
echo   Address : %HOST%
echo   URL     : %URL%
if "!LANMODE!"=="1" echo   Access  : LAN (other computers allowed)
if "!LANMODE!"=="0" echo   Access  : Local only
echo ---------------------------------------------
echo.
pause

REM ---------- Write config.txt ----------
echo [config] Writing config.txt
(
  echo # Part No. Generator configuration.
  echo # Generated by setup.bat - safe to edit by hand if you know what you're doing.
  echo # Changes take effect next time start.bat is run.
  echo HOST=%HOST%
  echo PORT=1030
  echo BIND=%BINDADDR%
  echo USE_PORT_80=%USE_PORT_80%
) > config.txt
echo [config] Done.

REM ---------- Build database if missing ----------
if exist "data.sqlite" (
  echo [db]     data.sqlite already exists. Leaving it untouched.
  echo          ^(Use option 2 from the menu to rebuild it.^)
) else (
  echo [db]     data.sqlite not found. Building from seed_data.py...
  python -c "import server; server.create_fresh_db()"
  if !errorlevel!==0 (
    echo [db]     ERROR: could not build data.sqlite. Is Python installed and on PATH?
  )
)

REM ---------- Add hosts entry ----------
set "HOSTS_FILE=%SystemRoot%\System32\drivers\etc\hosts"
findstr /I /C:"%HOST%" "%HOSTS_FILE%" >nul 2>nul
if !errorlevel!==0 (
  echo [hosts]  Entry for %HOST% already exists. Skipping.
) else (
  echo [hosts]  Adding: 127.0.0.1    %HOST%
  echo.>> "%HOSTS_FILE%"
  echo 127.0.0.1    %HOST%>> "%HOSTS_FILE%"
  if !errorlevel!==0 (
    echo [hosts]  Added successfully.
  ) else (
    echo [hosts]  ERROR: Could not write to the hosts file.
  )
)

REM ---------- Port 80 forwarding ----------
if "!USE_PORT_80!"=="1" (
  echo.
  echo [port 80] Checking whether port 80 is free...
  netstat -ano | findstr ":80 " | findstr "LISTENING" >nul 2>nul
  if !errorlevel!==0 (
    echo [port 80] WARNING: Something is already listening on port 80.
    echo           Port forwarding will NOT be set up.
    echo           You can still reach the app at:
    echo             http://%HOST%:1030
  ) else (
    netsh interface portproxy delete v4tov4 listenaddress=127.0.0.1 listenport=80 >nul 2>nul
    netsh interface portproxy add v4tov4 listenaddress=127.0.0.1 listenport=80 connectaddress=127.0.0.1 connectport=1030 >nul
    if !errorlevel!==0 (
      echo [port 80] Rule added: 127.0.0.1:80 -^> 127.0.0.1:1030
    ) else (
      echo [port 80] ERROR: Failed to add forwarding rule.
    )
  )
) else (
  echo.
  echo [port 80] Skipped. Removing any previous forwarding rule...
  netsh interface portproxy delete v4tov4 listenaddress=127.0.0.1 listenport=80 >nul 2>nul
)

REM ---------- Firewall rule for LAN ----------
if "!LANMODE!"=="1" (
  echo.
  echo [firewall] Allowing inbound port 1030 on private networks...
  netsh advfirewall firewall delete rule name="Part No. Generator" >nul 2>nul
  netsh advfirewall firewall add rule name="Part No. Generator" dir=in action=allow protocol=TCP localport=1030 profile=private >nul
  if !errorlevel!==0 (
    echo [firewall] Rule added.
  ) else (
    echo [firewall] ERROR: Could not add firewall rule.
  )
) else (
  echo.
  echo [firewall] Skipped (local-only mode).
)

echo.
echo [dns]    Flushing DNS cache...
ipconfig /flushdns >nul

echo.
echo ============================================
echo   Setup complete
echo ============================================
echo.
echo   The app will be available at:
echo     %URL%
echo.
echo   To start it: double-click start.bat
echo.
pause
exit /b 0


:REPAIR
echo.
echo ============================================
echo   Repair / Reset database
echo ============================================
echo.
echo This will DELETE the existing data.sqlite and rebuild it
echo from seed_data.py. Any changes you made in the app will
echo be lost.
echo.
echo Type YES to confirm, anything else to cancel.
set "CONFIRM="
set /p "CONFIRM=Confirm: "
if /i not "!CONFIRM!"=="YES" (
  echo Cancelled.
  pause
  exit /b 0
)

echo.
echo [db]     Rebuilding data.sqlite from seed_data.py...
python -c "import server; server.create_fresh_db()"
if !errorlevel!==0 (
  echo [db]     ERROR: rebuild failed. Is Python installed and on PATH?
  pause
  exit /b 1
)
echo [db]     Done.
echo.
echo ============================================
echo   Database rebuilt. Restart start.bat to pick up the changes.
echo ============================================
echo.
pause
exit /b 0


:UPDATESEED
echo.
echo ============================================
echo   Update seed_data.py from current database
echo ============================================
echo.
echo This will read the current data.sqlite and OVERWRITE
echo seed_data.py with its contents. This is how you capture
echo whatever you have in the app as the new built-in defaults.
echo.
echo Type YES to confirm, anything else to cancel.
set "CONFIRM="
set /p "CONFIRM=Confirm: "
if /i not "!CONFIRM!"=="YES" (
  echo Cancelled.
  pause
  exit /b 0
)

echo.
echo [seed]   Reading data.sqlite and rewriting seed_data.py...
python -c "import seed_tools; seed_tools.export_from_db()"
if !errorlevel!==0 (
  echo [seed]   ERROR: export failed. Is Python installed and on PATH?
  pause
  exit /b 1
)
echo [seed]   Done.
echo.
echo ============================================
echo   seed_data.py updated. The new defaults are now
echo   what Repair/Reset will restore.
echo ============================================
echo.
pause
exit /b 0